const API='/api';let token=null,notes=[],active=null,folder='all',query='';
const $=id=>document.getElementById(id);const login=$('login'),app=$('app');
function esc(s=''){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function date(x){return new Date(x).toLocaleDateString([],{month:'short',day:'numeric',year:'numeric'})}
async function api(path,opt={}){opt.headers={...(opt.headers||{}),Authorization:`Bearer ${token}`,'Content-Type':'application/json'};let r=await fetch(API+path,opt);if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
async function start(){token=localStorage.getItem('poetry_token');if(!token)return;try{let u=await api('/me');$('userName').textContent=u.login;login.classList.add('hidden');app.classList.remove('hidden');await refresh()}catch(e){localStorage.removeItem('poetry_token');token=null}}
$('loginBtn').onclick=()=>location.href=API+'/login';
function render(){let arr=notes.filter(n=>folder==='favorites'?n.favorite:folder==='drafts'?!n.body.trim():true).filter(n=>(n.title+' '+n.body).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.updated-a.updated);$('folderTitle').textContent={all:'All Notes',favorites:'Favorites',drafts:'Drafts'}[folder];$('count').textContent=`${arr.length} ${arr.length===1?'Note':'Notes'}`;$('allCount').textContent=notes.length;$('favCount').textContent=notes.filter(n=>n.favorite).length;$('draftCount').textContent=notes.filter(n=>!n.body.trim()).length;$('notes').innerHTML=arr.map(n=>`<article class="note ${active===n.id?'selected':''}" data-id="${n.id}"><h3>${esc(n.title||'Untitled Note')} ${n.favorite?'<span class="star">★</span>':''}</h3><p>${esc((n.body||'No additional text').replace(/\s+/g,' ').trim())}</p><time>${date(n.updated)}</time></article>`).join('');$('empty').classList.toggle('hidden',arr.length>0);document.querySelectorAll('.note').forEach(x=>x.onclick=()=>open(x.dataset.id))}
async function refresh(){notes=await api('/notes');render()}
async function open(id){active=id;let n=notes.find(x=>x.id===id);$('title').value=n.title;$('body').value=n.body;$('favorite').textContent=n.favorite?'★':'☆';$('meta').textContent=`Created ${date(n.created)} · Last edited ${date(n.updated)}`;$('editor').classList.add('open');render()}
let saveTimer;function edit(){clearTimeout(saveTimer);saveTimer=setTimeout(async()=>{if(!active)return;let n=notes.find(x=>x.id===active);n.title=$('title').value;n.body=$('body').value;try{let saved=await api('/notes/'+active,{method:'PUT',body:JSON.stringify({title:n.title,body:n.body})});Object.assign(n,saved);$('meta').textContent=`Created ${date(n.created)} · Last edited ${date(n.updated)}`;render()}catch(e){console.error(e)}},400)}
async function create(){let n=await api('/notes',{method:'POST',body:JSON.stringify({title:'',body:''})});notes.unshift(n);open(n.id);$('title').focus()}
async function favorite(){if(!active)return;let n=notes.find(x=>x.id===active);let saved=await api('/notes/'+active,{method:'PUT',body:JSON.stringify({favorite:!n.favorite})});Object.assign(n,saved);$('favorite').textContent=n.favorite?'★':'☆';render()}
$('newBtn').onclick=$('newBtn2').onclick=$('emptyNew').onclick=create;$('title').oninput=$('body').oninput=edit;$('favorite').onclick=favorite;$('done').onclick=$('back').onclick=()=>{$('editor').classList.remove('open');active=null;render()};$('delete').onclick=()=>active&&$('modal').classList.remove('hidden');$('cancel').onclick=()=>$('modal').classList.add('hidden');$('confirm').onclick=async()=>{await api('/notes/'+active,{method:'DELETE'});$('modal').classList.add('hidden');$('editor').classList.remove('open');active=null;await refresh()};$('search').oninput=e=>{query=e.target.value;render()};document.querySelectorAll('.folder').forEach(x=>x.onclick=()=>{folder=x.dataset.folder;document.querySelector('.folder.active').classList.remove('active');x.classList.add('active');$('sidebar').classList.remove('open');render()});$('openSide').onclick=()=>$('sidebar').classList.add('open');$('logoutBtn').onclick=()=>{localStorage.removeItem('poetry_token');location.reload()};start();
