const express=require('express'),session=require('cookie-session'),{Octokit}=require('@octokit/rest');const app=express();app.use(express.json());app.use(session({name:'poetry_session',keys:[process.env.SESSION_SECRET||'change-me'],httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production'}));const G={owner:process.env.GITHUB_OWNER,repo:process.env.GITHUB_REPO||'poetry-notes',dir:process.env.GITHUB_POEMS_DIR||'poems'};
app.get('/api/login',(req,res)=>{let p=new URLSearchParams({client_id:process.env.GITHUB_CLIENT_ID,scope:'repo',redirect_uri:process.env.GITHUB_REDIRECT_URI});res.redirect('https://github.com/login/oauth/authorize?'+p)});
app.get('/api/callback',async(req,res)=>{try{let r=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:process.env.GITHUB_CLIENT_ID,client_secret:process.env.GITHUB_CLIENT_SECRET,code:req.query.code,redirect_uri:process.env.GITHUB_REDIRECT_URI})});let j=await r.json();if(!j.access_token)throw Error('OAuth failed');req.session.token=j.access_token;res.redirect(process.env.FRONTEND_URL||'/')}catch(e){res.status(500).send('GitHub login failed')}});
function auth(req,res,next){if(!req.session.token)return res.status(401).json({error:'unauthorized'});req.octokit=new Octokit({auth:req.session.token});next()}
async function list(req){let o=G;let files=await req.octokit.paginate(req.octokit.repos.getContent,{owner:o.owner,repo:o.repo,path:o.dir,per_page:100});return files.filter(x=>x.name.endsWith('.json'))}
async function get(req,name){let r=await req.octokit.repos.getContent({owner:G.owner,repo:G.repo,path:`${G.dir}/${name}`});return {sha:r.data.sha,data:JSON.parse(Buffer.from(r.data.content,'base64').toString())}}
app.get('/api/me',auth,async(req,res)=>{let u=await req.octokit.users.getAuthenticated();res.json({login:u.data.login})});
app.get('/api/notes',auth,async(req,res)=>{let fs=await list(req),out=[];for(let f of fs){try{let x=await get(req,f.name);out.push(x.data)}catch{}}res.json(out)});
app.post('/api/notes',auth,async(req,res)=>{let id=crypto.randomUUID(),now=Date.now(),data={id,title:req.body.title||'',body:req.body.body||'',favorite:false,created:now,updated:now};let path=`${G.dir}/${id}.json`;await req.octokit.repos.createOrUpdateFileContents({owner:G.owner,repo:G.repo,path,message:`Add poem ${id}`,content:Buffer.from(JSON.stringify(data,null,2)).toString('base64')});res.status(201).json(data)});
app.put('/api/notes/:id',auth,async(req,res)=>{let f=await get(req,`${req.params.id}.json`),d={...f.data,...req.body,updated:Date.now()};await req.octokit.repos.createOrUpdateFileContents({owner:G.owner,repo:G.repo,path:`${G.dir}/${req.params.id}.json`,sha:f.sha,message:`Update poem ${req.params.id}`,content:Buffer.from(JSON.stringify(d,null,2)).toString('base64')});res.json(d)});
app.delete('/api/notes/:id',auth,async(req,res)=>{let f=await get(req,`${req.params.id}.json`);await req.octokit.repos.deleteFile({owner:G.owner,repo:G.repo,path:`${G.dir}/${req.params.id}.json`,sha:f.sha,message:`Delete poem ${req.params.id}`});res.status(204).end()});
app.listen(process.env.PORT||3000);
